In [9]:
from dotenv import load_dotenv
from src.api.coingecko_client import CoinGeckoClient
from src.database.postgres_manager import DatabaseManager
from src.ml.btc_predictor import BTCPredictor
from src.pipeline.btc_pipeline import BTCDataPipeline
from src.config.settings import get_postgres_settings, get_coingecko_settings

In [10]:
load_dotenv()

True

In [13]:
pg_settings = get_postgres_settings()
cg_settings = get_coingecko_settings()

In [15]:
api_client = CoinGeckoClient(API_KEY=cg_settings.API_KEY, timeout=10)

In [16]:
db_manager = DatabaseManager(settings=pg_settings)

In [17]:
predictor = BTCPredictor()

In [18]:
pipeline = BTCDataPipeline(api_client, db_manager, predictor)

In [19]:
df_api = pipeline.fetch_data("2025-01-01", "2025-12-31")
print(f"Datos desde la API: {len(df_api)}")
df_api.head()

HTTPError: 401 Client Error: Unauthorized for url: https://api.coingecko.com/api/v3/coins/bitcoin/market_chart/range?vs_currency=usd&from=1735689600&to=1767139200

In [28]:
import pandas as pd

In [43]:
df= pd.read_csv('BTCUSD_1d_Binance.csv')

In [30]:
df.head()

             Open time  ... Ignore
0  2017-08-17 04:00:00  ...    0.0
1  2017-08-18 00:00:00  ...    0.0
2  2017-08-19 00:00:00  ...    0.0
3  2017-08-20 00:00:00  ...    0.0
4  2017-08-21 00:00:00  ...    0.0

[5 rows x 12 columns]

In [44]:
print(df.columns.tolist())

['Open time', 'Close time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Quote asset volume', 'Number of trades', 'Taker buy base asset volume', 'Taker buy quote asset volume', 'Ignore']

In [46]:
print(df.dtypes)

Open time                        object
Close time                       object
Open                            float64
High                            float64
Low                             float64
Close                           float64
Volume                          float64
Quote asset volume              float64
Number of trades                float64
Taker buy base asset volume     float64
Taker buy quote asset volume    float64
Ignore                          float64
dtype: object

In [47]:
print(df['Close'].head(10))

0    4285.08
1    4108.37
2    4139.98
3    4086.29
4    4016.00
5    4040.00
6    4114.01
7    4316.01
8    4280.68
9    4337.44
Name: Close, dtype: float64

In [1]:
# Convert column
df['Open time']=pd.to_datetime(df['Open time'])

NameError: name 'pd' is not defined

In [2]:
start_date = '2025-01-01'
end_date = '2025-09-30'

# Create mask using the column date
mask = (df['Open time'] >= start_date) & (df['Open time'] <= end_date)
df_filtered = df.loc[mask]

print(f"Registros del rango: {len(df_filtered)}")

NameError: name 'df' is not defined

In [ ]:
precios_cierre = df_filtered['Close'].values
print(precios_cierre[:10])

[ 94591.79  96984.79  98174.18  98220.5   98363.61 102235.6   96954.61
  95060.61  92552.49  94726.11]

In [3]:
from src.database.postgres_manager import DatabaseManager
from src.config.settings import get_postgres_settings

In [4]:
pg_settings = get_postgres_settings()

db_manager = DatabaseManager(settings=pg_settings)

In [5]:
df = db_manager.get_btc_prices("2025-10-01", "2025-12-31")

Error connecting to PostgreSQL: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
Database read permission error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
df["date"].value_counts().to_dict()

{datetime.date(2025, 12, 1): 1309,
 datetime.date(2025, 12, 2): 1309,
 datetime.date(2025, 12, 3): 1309,
 datetime.date(2025, 12, 4): 1309,
 datetime.date(2025, 12, 6): 1285,
 datetime.date(2025, 12, 5): 1285,
 datetime.date(2025, 12, 7): 1285,
 datetime.date(2025, 12, 8): 1285,
 datetime.date(2025, 12, 11): 1285,
 datetime.date(2025, 12, 10): 1285,
 datetime.date(2025, 12, 9): 1285,
 datetime.date(2025, 12, 12): 1261,
 datetime.date(2025, 12, 14): 1261,
 datetime.date(2025, 12, 13): 1261,
 datetime.date(2025, 12, 15): 973,
 datetime.date(2025, 12, 16): 973,
 datetime.date(2025, 12, 19): 973,
 datetime.date(2025, 12, 18): 973,
 datetime.date(2025, 12, 17): 973,
 datetime.date(2025, 11, 9): 781,
 datetime.date(2025, 11, 2): 781,
 datetime.date(2025, 11, 3): 781,
 datetime.date(2025, 11, 4): 781,
 datetime.date(2025, 11, 5): 781,
 datetime.date(2025, 11, 1): 781,
 datetime.date(2025, 11, 12): 781,
 datetime.date(2025, 11, 11): 781,
 datetime.date(2025, 11, 10): 781,
 datetime.date(2025, 11, 14): 781,
 datetime.date(2025, 11, 15): 781,
 datetime.date(2025, 11, 16): 781,
 datetime.date(2025, 11, 29): 781,
 datetime.date(2025, 11, 25): 781,
 datetime.date(2025, 11, 28): 781,
 datetime.date(2025, 11, 27): 781,
 datetime.date(2025, 11, 26): 781,
 datetime.date(2025, 11, 21): 781,
 datetime.date(2025, 11, 20): 781,
 datetime.date(2025, 11, 19): 781,
 datetime.date(2025, 11, 18): 781,
 datetime.date(2025, 11, 17): 781,
 datetime.date(2025, 11, 24): 781,
 datetime.date(2025, 11, 23): 781,
 datetime.date(2025, 11, 22): 781,
 datetime.date(2025, 11, 30): 781,
 datetime.date(2025, 11, 8): 781,
 datetime.date(2025, 11, 7): 781,
 datetime.date(2025, 11, 6): 781,
 datetime.date(2025, 11, 13): 781,
 datetime.date(2025, 10, 31): 757,
 datetime.date(2025, 10, 30): 733,
 datetime.date(2025, 10, 20): 733,
 datetime.date(2025, 10, 28): 733,
 datetime.date(2025, 10, 27): 733,
 datetime.date(2025, 10, 26): 733,
 datetime.date(2025, 10, 25): 733,
 datetime.date(2025, 10, 24): 733,
 datetime.date(2025, 10, 23): 733,
 datetime.date(2025, 10, 22): 733,
 datetime.date(2025, 10, 21): 733,
 datetime.date(2025, 10, 29): 733,
 datetime.date(2025, 10, 19): 637,
 datetime.date(2025, 10, 17): 637,
 datetime.date(2025, 10, 15): 637,
 datetime.date(2025, 10, 18): 637,
 datetime.date(2025, 10, 16): 637,
 datetime.date(2025, 10, 12): 445,
 datetime.date(2025, 10, 14): 445,
 datetime.date(2025, 10, 13): 445,
 datetime.date(2025, 10, 5): 397,
 datetime.date(2025, 10, 7): 397,
 datetime.date(2025, 10, 6): 397,
 datetime.date(2025, 10, 8): 397,
 datetime.date(2025, 10, 9): 397,
 datetime.date(2025, 10, 10): 397,
 datetime.date(2025, 10, 11): 397,
 datetime.date(2025, 10, 4): 277,
 datetime.date(2025, 10, 3): 277,
 datetime.date(2025, 10, 2): 277,
 datetime.date(2025, 10, 1): 277,
 datetime.date(2025, 12, 20): 277,
 datetime.date(2025, 12, 21): 277,
 datetime.date(2025, 12, 22): 277,
 datetime.date(2025, 12, 23): 277,
 datetime.date(2025, 12, 24): 277,
 datetime.date(2025, 12, 25): 277,
 datetime.date(2025, 12, 26): 277,
 datetime.date(2025, 12, 27): 277,
 datetime.date(2025, 12, 28): 277,
 datetime.date(2025, 12, 29): 277,
 datetime.date(2025, 12, 30): 61,
 datetime.date(2025, 12, 31): 37}

In [ ]:
df

             date      price_usd
0      2025-10-01  117481.287601
1      2025-10-01  117273.633764
2      2025-10-01  116868.506493
3      2025-10-01  117704.379056
4      2025-10-01  117484.314214
...           ...            ...
66399  2025-12-31   87611.878669
66400  2025-12-31   87409.559581
66401  2025-12-31   88414.628561
66402  2025-12-31   88414.628561
66403  2025-12-31   88414.628561

[66404 rows x 2 columns]

In [ ]:
from src.pipeline.btc_pipeline import BTCDataPipeline

In [ ]:
pipeline =

In [ ]:
df_train = pipeline.get_data_for_training(train_start, train_end)

NameError: name 'pipeline' is not defined

In [ ]:
fetc